
services:
  app:
    container_name: pretix_app
    build:
      dockerfile: Dockerfile
      context: ./docker/pretix
    restart: always
    depends_on:
      - database
      - cache
    volumes:
      - pretix_data:/data
      - ./docker/pretix/pretix.cfg:/etc/pretix/pretix.cfg
      - ./docker/pretix/crontab:/tmp/crontab
    environment:
      - PRETIX_DB_HOST=database
      - PRETIX_DB_NAME=${POSTGRES_DB:-pretix}
      - PRETIX_DB_USER=${POSTGRES_USER:-pretix}
      - PRETIX_DB_PASSWORD=${POSTGRES_PASSWORD:-pretix}
      - PRETIX_REDIS_URL=redis://cache/0
      - PRETIX_CELERY_BROKER_URL=redis://cache/2
      - PRETIX_CELERY_BACKEND_URL=redis://cache/1
      - PRETIX_EMAIL_HOST=${EMAIL_HOST:-}
      - PRETIX_EMAIL_PORT=${EMAIL_PORT:-587}
      - PRETIX_EMAIL_USER=${EMAIL_USER:-}
      - PRETIX_EMAIL_PASSWORD=${EMAIL_PASSWORD:-}
      - PRETIX_EMAIL_FROM=${EMAIL_FROM:-noreply@example.com}
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pretix.rule=Host(`${DOMAIN:-pretix.localhost}`)"
      - "traefik.http.routers.pretix.entrypoints=web,websecure"
      - "traefik.http.routers.pretix.tls=true"
      - "traefik.http.services.pretix.loadbalancer.server.port=80"
      - "traefik.docker.network=backend"

  database:
    image: postgres:17-alpine3.22
    container_name: database
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-pretix}
      - POSTGRES_USER=${POSTGRES_USER:-pretix}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pretix}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  cache:
    image: redis:alpine3.22
    container_name: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  postgres_data:
    driver: local
  pretix_data:
    driver: local
  redis_data:
    driver: local

networks:
  backend:
    driver: bridge